version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  load:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    depends_on:
      - db
    environment:
      - WAIT_HOSTS=db:5432

volumes:
  pgdata:
